
export const LOAD_CARDS = 'LOAD_CARDS'
export const RATE_NUMBER = 'RATE_NUMBER'
export const SEARCH_OPTIONS = 'SEARCH_OPTIONS'
export const SEARCH_DROPDOWN = 'SEARCH_DROPDOWN'
export const SEARCH_DATE = 'SEARCH_DATE'